### ISSUE TITLE
Nat.audio.play 在IOS11播放远程MP3文件报错

### ISSUE THREAD

**Issue by john2088** [natjs/nat#11]
CredStore - performQuery - Error copying matching creds.  Error=-25300, query={
    class = inet;
    "m_Limit" = "m_LimitAll";
    "r_Attributes" = 1;
    sync = syna;
}

**Comment by Acathur** [comment]
iOS11下播放远程音频文件正常，请提供调用代码和音频文件链接

**Comment by john2088** [comment]
Nat.audio.play('http://cdn.instapp.io/nat/samples/audio.mp3')
在ip6 plus上调式，调用任何网络音频都会报这个错，直接调用本地没问题.
但用Xcode的虚拟机没问题，应该是手机问题
xcode Version 9.0 (9A235)
IOS 11.0.2 iphone6 plus 港行版

**Comment by Acathur** [comment]
目测是Xcode问题，测试build后ipk安装不会发生

**Comment by Suzy1993** [comment]
我也遇到了在IOS11播放远程MP3文件报错，但本地MP3文件没有问题的情况，想知道大佬们最终怎么解决的？
