### ISSUE TITLE
已有项目集成的操作方式?

### ISSUE THREAD

**Issue by phoenixsky** [natjs/nat#22]
RT,没有已有项目集成的操作方式么?类似android通过gradle 添加依赖的方式 或者iOS通过pods的方式?

在Nat-Explorer项目里发现有依赖的方式,文档中怎么不提出来呢?

**Comment by Acathur** [comment]
请参考weex集成方案: [集成 Weex 到已有应用](http://weex-project.io/cn/guide/integrate-to-your-app.html)

**Comment by phoenixsky** [comment]
之前没有描述清楚, 我在已有项目里,想使用nat的一些功能.查了nat-explorer的代码.在weexplugin目录里发现了需要的代码.想了解为什么不把weexplugin代码 发布到jcenter中,这样可以在build中直接引入就可以了

**Comment by Acathur** [comment]
Jcenter: https://bintray.com/natjs/nat/ (NOTICE: without weex plugin wrapper)

**Comment by phoenixsky** [comment]
嗯?  为什么jcenter中没有weexplugi?.

**Comment by Acathur** [comment]
weex plugin 仅适用于 weex 项目，故仅发布于 weex market
