### ISSUE TITLE
natjs plugins no longer compatible with weexpack? "This package of weex is not support anymore! Please choose other package."

### ISSUE THREAD

**Issue by fumpierrez** [natjs/nat#24]
Hi

Looks like newest weexpack is no longer compatible with natjs (it also happens with weex-svg so possibly weexpack has broken compatibility downwards) 

It happens for all nat-* plugins I've tried

```
weexpack plugin add nat-transfer
14:19:51 : This package of weex is not support anymore! Please choose other package.
```

weex --version
   v1.2.6
 - weexpack : v1.0.2
 - weex-builder : v0.3.12
 - weex-previewer : v1.4.4

Mac Sierra 10.12.4

**Comment by Acathur** [comment]
Please switch the `weexpack` to old version (less than v1.0.0) temporarily, we will contact to weex team to solve this problem

**Comment by fumpierrez** [comment]
Hi @Acathur sorry to insist, is there any update or ETA on this? thanks

**Comment by Acathur** [comment]
@fumpierrez All the nat plugins will be updated this week

**Comment by hoatructhanhlam** [comment]
I hope to receive now to update. Thanks for trying.
Can you build add plugin scan QR code plugin for weex?

**Comment by hoatructhanhlam** [comment]
nearly weekend, and no see updation. to Lunar new year...........:(

**Comment by yangyueyul** [comment]
Hi @Acathur, hope to receive update before new year :(

**Comment by Acathur** [comment]
Still in progress, just wait for JCenter admin to update packages info

**Comment by Acathur** [comment]
Update: all the iOS version plugins has been updated. Use `weex plugin add [nat module]` to add the plugins to your project

**Comment by Acathur** [comment]
Update: Android versions ready

**Comment by hoatructhanhlam** [comment]
Thank you! 
We expect to add scanqr code plugin soon

**Comment by zczhaichao** [comment]
weexpack 版本1.2.7
目前weepack plugin add weex-amap显示
This package of weex is not support anymore! Please choose other package.
