### ISSUE TITLE
Couldn't find preset "env"

### ISSUE THREAD

**Issue by weenta** [natjs/nat#25]
when `npm run build`
` ERROR in ./node_modules/_natjs@0.1.3@natjs/lib/index.js
    Module build failed:
Error: Couldn't find preset "env" relative to directory "E:\\...\\node_modules\\_natjs@0.1.3@natjs"`

---
environment
win7
node 6.9.5
npm 5.0.4
weexpack 1.1.1

**Comment by Acathur** [comment]
Please use `npm i -D babel-preset-env` to solve the problem temporarily, we will release a new version soon. @weenta

**Comment by Acathur** [comment]
fixed. use `npm i natjs` to update your nat to the latest version (`>=0.1.5`)
