### ISSUE TITLE
Unhandled promise rejection TypeError:undefined is not an object(evaluating 'camera.captureImage')

### ISSUE THREAD

**Issue by baixiaodu** [natjs/nat#27]
environment:
window: 10
node 8.9.3
npm 5.6
weexpack 1.1.1
natjs 0.1.5

what's wrong with me???
/plugins.json
![image](https://user-images.githubusercontent.com/22970149/36774576-a03f9932-1c99-11e8-99a7-9feaa04dd29a.png)

.weex_plugin.json
![image](https://user-images.githubusercontent.com/22970149/36774548-84293a14-1c99-11e8-8cec-21ebc116e7cc.png)
 
index.vue  

![image](https://user-images.githubusercontent.com/22970149/36774666-f27226d4-1c99-11e8-8ac3-f3431416233e.png)

**Comment by Acathur** [comment]
@baixiaodu maybe you should handle the error condition (`err`), it seems you've got an error then `ret` is `undefined`

**Comment by sushilparajuli** [comment]
@Acathur, I got the same issue as @baixiaodu is getting. Also implement error condition too like below but the app is crashing :
```
Nat.camera.captureImage({}, (err, ret) => {
          if(err){
            modal.toast({message: JSON.stringify(err), duration: 0.5});
          }
          this.imageData = ret.path
        })
```
