### ISSUE TITLE
NatJs Plugin installation issue after updating weex environment

### ISSUE THREAD

**Issue by sushilparajuli** [natjs/nat#28]
`$ weexpack plugin add nat-modal`
Fetching plugin "nat-modal" via npm
Error during untar for /Users/sushilparajuli/.cordova/lib/npm_cache/nat-modal/1.0.1-alpha/package.tgz: Error: EACCES: permission denied, open '/Users/sushilparajuli/.cordova/lib/npm_cache/nat-modal/1.0.1-alpha/package/ios/Pods/NatModal/ios/Classes/NatModal.h'
Error: Failed to fetch plugin nat-modal via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
Error: EACCES: permission denied, open '/Users/sushilparajuli/.weexpack/lib/npm_cache/nat-modal/1.0.1-alpha/package/ios/Pods/NatModal/ios/Classes/NatModal.h'

**Tried Sudo**
`sudo weexpack plugin add nat-modal`
Password:
Fetching plugin "nat-modal" via npm
Error: Cannot find plugin.xml for plugin "package". Please try adding it again.

Spec:
- weex:  v1.2.9
- weexpack : v1.1.5
 - weex-builder : v0.3.14
 - weex-previewer : v1.4.6

**Comment by Acathur** [comment]
try `weex plugin add nat-modal`, if not work please re-init your weex project

**Comment by sushilparajuli** [comment]
Thanks, re-init seems working for me
