### ISSUE TITLE
插件添加成功 使用不了 

### ISSUE THREAD

**Issue by heshan-song** [natjs/nat#32]
我第一次 使用weex 构建项目 
安装nat插件， 安装了natjs  然后 安装 我 运行 weexpack plugin add nat-media-image

在plugins 目录下 有一个 json 文件
里面是 是一些 插件 列表 
{
      "type": "maven",
      "groupId": "com.instapp.nat",
      "name": "weex-plugin-media-image",
      "version": "1.0.1",
      "dependency": "com.instapp.nat:weex-plugin-media-image:1.0.1"
    },

但是 我发现platforms 平台里面的 ios  安卓 目录 里面 没有 所谓的 weex-plugin-media-image 项目，我在vue 页面 也调用不了，是怎么会呢？

**Comment by sushilparajuli** [comment]
@heshan-song ,  Try `weex plugin add nat-media-image `. I had similar issue using weexpack  but using weex add works fine

**Comment by heshan-song** [comment]
@sushilparajuli  , D:\xuexi\weex\demo-all-02>weex plugin add nat-media-image
This plugin support for Android,iOS platforms.
17:01:17 : nat-media-image has installed success in Android project.
17:01:17 : if you want to update it, please use `weex plugin update` command.
17:01:17 : nat-media-image has installed success in iOS project.
17:01:17 : if you want to update it, please use `weex plugin update` command.

Prompt installation is successful, but it still can't run

**Comment by sushilparajuli** [comment]
@heshan-song , Can you post your issue screenshot/gif here so I can help? I am successfully running on latest weex environment .

**Comment by heshan-song** [comment]
@sushilparajuli  ![qq 20180328150314](https://user-images.githubusercontent.com/22375125/38013930-7f9ed308-3299-11e8-8ab0-e91eb54edcc8.png)
Prompt installation is successful,  

There is no'weex-plugin-media-image'plug-in project in the'plugins' directory

Please give me one of your engineering catalogues, or give me a 'demo'. I'll refer to it, OK, thank you.

**Comment by sushilparajuli** [comment]
@heshan-song , I think you should probably check out this repo: https://github.com/natjs/nat-explorer and post your code implementation error like How are you calling the method and getting an error?  I am just running successfully into my latest weex and interested to help you. Thanks

**Comment by heshan-song** [comment]
@sushilparajuli  , thank you. thank you. thank you.

**Comment by luanxuechao** [comment]
@heshan-song   你解决了这个问题了吗？ 我也遇到了

**Comment by acathur** [comment]
@heshan-song @luanxuechao please provide your logs

**Comment by luanxuechao** [comment]
no logs  terminal show success  but not found

**Comment by luanxuechao** [comment]
<img width="381" alt="7fe58e62142cd6cf39c6b6631d08265b" src="https://user-images.githubusercontent.com/13465762/38778183-0cbb40bc-40e8-11e8-84ed-69b9fa6f2fb5.png">
<img width="597" alt="413622d47bd143addab7e4d44ddcf9ac" src="https://user-images.githubusercontent.com/13465762/38778185-15274458-40e8-11e8-8857-179a3e164e32.png">
can you  give me some advance ,my email address luanxuechaowd@gmail.com, look forword you reply

**Comment by acathur** [comment]
@luanxuechao please check your `weex-toolkit` version (use `weex -v`), make sure your `weex-toolkit`'s version is `v1.x` and your weex project is created by the newest version

**Comment by luanxuechao** [comment]
@Acathur  是的
![1523966472888](https://user-images.githubusercontent.com/13465762/38868587-1d264ddc-427a-11e8-9f1d-3fa74d84ac6e.jpg)

**Comment by zhangjanp** [comment]
https://github.com/alibaba/weex/issues/3156
@heshan-song

**Comment by acathur** [comment]
@luanxuechao 插件安装正确吗？`weex plugin add nat-camera` (注意调用摄像头的插件是`camera`，而非`media-image`)
