### ISSUE TITLE
natjs 怎么上传文件夹

### ISSUE THREAD

**Issue by zhengwenhao2017** [natjs/nat#36]
![aaaaaaaa](https://user-images.githubusercontent.com/39073315/39733883-5bd8a57e-52a7-11e8-9e09-e0b0ed0c3f58.png)

**Comment by zhengwenhao2017** [comment]
![Uploading aaaaaaaa.png…]()

**Comment by guoquancaho** [comment]
打开本地存储的这个  也是用nat做的么？用哪个方法啊

**Comment by zhengwenhao2017** [comment]
不知道用什么做

**Comment by acathur** [comment]
nat组件暂不支持上传文件夹

**Comment by zhengwenhao2017** [comment]
那有什么好的,解决方法吗
