### ISSUE TITLE
MultiImageSelector  createIntent

### ISSUE THREAD

**Issue by guoquancaho** [natjs/nat#39]
提供了！
MultiImageSelector createIntent方法：
Intent intent = new Intent(Intent.ACTION_PICK, MediaStore.Images.Media.EXTERNAL_CONTENT_URI);
intent.setDataAndType(MediaStore.Images.Media.EXTERNAL_CONTENT_URI, "image/*");
我使用这种方式可以打开相册 选择照片 和 获取路径无法正常工作

源码中的：
Intent intent = new Intent(context, MultiImageSelectorActivity.class);
方式永远打开的是sdcard

**Comment by acathur** [comment]
Same as #38
