### ISSUE TITLE
[Android]nat.transfer download failed

### ISSUE THREAD

**Issue by zhangfei56** [natjs/nat#42]
code line 156: outputStream = new FileOutputStream(fileFinal); 
Error information: java.io.FileNotFoundException: /storage/emulated/0/102-1235614960-43-75-119-60-56679724103490.6537333 (Permission denied)
Add permission:    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/>

**Comment by acathur** [comment]
Please check the permission in `AndroidManifest.xml`, and also see #41

**Comment by zhangfei56** [comment]
已解决！ thx！
