### ISSUE TITLE
transfer upload error

### ISSUE THREAD

**Issue by diuqilei** [natjs/nat#43]
环境：iPhone 6s, iOS 10.3.2

Xcode报错信息：
<Weex>[error]WXJSCoreBridge.m:146, jsLog: Unhandled promise rejection {"msg":"UPLOAD_INVALID_ARGUMENT","code":153050}

其他：
安卓没报错

代码：
```
Nat.upload('上传接口', {
  path: '文件路径',
}, (error, response) => {
  if(error) {
    reject(error);
  } else {
    const data = response.data;
    const res = typeof data === 'string' ? JSON.parse(data) : data;
    if(res.errorCode === 100) {
      reject(res);
    } else {
      resolve(res);
    }
  }
});
```

**Comment by acathur** [comment]
检查一下上传`url`,`path`值是否正确, iOS文件路径仅支持从沙盒访问

**Comment by diuqilei** [comment]
@Acathur 问题解决了，确实是path出错了。之前弄安卓的时候在path前面加了file://（我也忘记为什么要这么做了），实际上不管安卓还是iOS，都是可以直接使用Nat.image.pick回调函数返回的path。谢谢大佬指导！

**Comment by reverseAndroid** [comment]
@gaalok 你好，问一下，我这里上传照片一直传不上去
![qq 20190227181047](https://user-images.githubusercontent.com/25810748/53539523-dd6d6c80-3b4c-11e9-92fc-7512cb33f392.png)
一直在报错，Unhandled promise rejection{"code":153000,"message":"UPLOAD_INTERNAL_ERROR"}，能不能帮我看看哪里有问题？
