### ISSUE TITLE
调用拍照的方法报错

### ISSUE THREAD

**Issue by yuan-gao** [natjs/nat#5]
Unhandled promise rejection TypeError: camera.captureImage is not a function. (In 'camera.captureImage', 'camera.captureImage' is undefined)

weex plugin add nat-camera
npm install natjs --save
[WXSDKEngine registerModule:@"camera" withClass:[NatCamera class]];
这三个步骤都做了

麻烦看下，谢谢！！！

**Comment by Acathur** [comment]
请更新`nat-camera`到最新版本 >= `0.1.6`后重新运行，并确保`natjs`>=`0.0.8`

```
weex plugin remove nat-camera
weex plugin add nat-camera
```

**Comment by yuan-gao** [comment]
执行 npm install nats 装的是0.0.6

**Comment by Acathur** [comment]
npm >= 5
```
npm uni natjs
npm i natjs
```
npm < 5
```
npm uni natjs
npm i -s natjs
```
