### ISSUE TITLE
Nat.audio.play在ios11中无法调用回调

### ISSUE THREAD

**Issue by weenta** [natjs/nat#55]
// ios11 回调并没有被调用
```js
Nat.audio.play('http://cdn.instapp.io/nat/samples/audio.mp3', (err) => {
        if (err) {
          Nat.toast('[ERROR] ' + JSON.stringify(err))
          return
        }

        Nat.toast('started')
      })

```

**Comment by weenta** [comment]
`Nat.video.play` 在ios11中有相同的问题
在android中以上两个都可以正常调用回调

**Comment by 13601313270** [comment]
我尝试的结果是，这个回调，没法监听初始化的那次播放。

当你执行Nat.audio.pause()，然后再执行Nat.audio.play，这一次可以触发回掉函数。
![image](https://user-images.githubusercontent.com/7564863/62437999-194dd300-b778-11e9-9d7b-f371a07d62b5.png)
通过看源码，好想实现上也确实是这样实现的，有oc基础的可以改一下源码

**Comment by weenta** [comment]
thanks for your help, appreciate it @13601313270
